packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  msw: true
catalog:
  vitest: ^5.0.0
  jsdom: ^30.0.1
  "@testing-library/jest-dom": ^7.0.1
  "@testing-library/react": ^16.3.3
  "@testing-library/user-event": ^14.6.7
